import turtle
import threading
from tfunctions import *

BASE = 110
BASE_HEIGHT = 35
SILVER = "silver"
FLAME = "tiny-fire.gif"

t = turtle.Turtle()
t2 = turtle.Turtle()
left_shamash = turtle.Turtle(visible=False)
right_shamash = turtle.Turtle(visible=False)
left_shamash.up()
right_shamash.up()
left_shamash.goto(-60, 160)
right_shamash.goto(-50, 160)
screen = turtle.Screen()
screen.register_shape(FLAME)
t.ht()
t2.ht()

left_shamash.width(5)
right_shamash.width(5)
t.width(5)
t2.width(5)

goBack(t, t2, BASE)
draw(t, SILVER, BASE)
t.lt(90)
t2.lt(90)
thread1 = threading.Thread(target=draw(t, SILVER, BASE_HEIGHT))
thread2 = threading.Thread(target=draw(t2, SILVER, BASE_HEIGHT))
turn1pens(t, t2, 90)
thread3 = threading.Thread(target=draw(t, SILVER, BASE_HEIGHT))
thread4 = threading.Thread(target=draw(t2, SILVER, BASE_HEIGHT))
turn1pens(t, t2, -90)
thread5 = threading.Thread(target=draw(t, SILVER, BASE_HEIGHT-10))
thread6 = threading.Thread(target=draw(t2, SILVER, BASE_HEIGHT-10))
turn1pens(t, t2, 90)
thread7 = threading.Thread(target=draw(t, SILVER, BASE_HEIGHT-10))
thread8 = threading.Thread(target=draw(t2, SILVER, BASE_HEIGHT-10))
turn1pens(t, t2, -90)
draw_pipe(t, t2, 100)
left_shamash.color(SILVER)
right_shamash.color(SILVER)
left_shamash.down()
right_shamash.down()
right_shamash.lt(90)
left_shamash.lt(90)
t.rt(90)
t2.lt(90)
draw_arc(t, t2, 110, 90)
plus_minus(t, t2)
draw_arc(t, t2, -100, 90)
minus_plus(t, t2)
draw_arc(t, t2, 90, 90)
plus_minus(t, t2)
draw_arc(t, t2, -80, 90)
minus_plus(t, t2)
draw_arc(t, t2, 70, 90)
plus_minus(t, t2)
draw_arc(t, t2, -60, 90)
minus_plus(t, t2)
draw_arc(t, t2, 50, 90)
plus_minus(t, t2)
draw_arc(t, t2, -40, 90)
left_shamash.fd(110)
right_shamash.fd(110)
right_shamash.lt(90)
right_shamash.fd(10)
t.shape(FLAME)
t2.shape(FLAME)
left_shamash.shape(FLAME)
draw_flame(t, -20)
draw_flame(t, 0)
draw_flame(t, 20)
draw_flame(t, 40)
draw_flame(left_shamash, -60)
draw_flame(t2, -100)
draw_flame(t2, -120)
draw_flame(t2, -140)
draw_flame(t2, -160)

turtle.mainloop()